spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: user
    password: secret
  sql.init.mode: always


logging.level.org.spring.framework.jdbc: debug

contact.service.url: https://jsonplaceholder.typicode.com/users

rabbitmq:
  queue.name: customer
  exchange.name: customer_exchange
  routing.key: customer_routing_key

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 5s
        timeoutDuration: 30s

